#################
### AUTOSTART ###
#################

exec-once = $terminal
exec-once = swaybg -i ~/.config/hypr/assets/3.jpg
exec-once = tmux setenv -g HYRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
