#################
### AUTOSTART ###
#################

exec-once = hyprlock -c ~/.config/hypr/lock.conf
exec-once = hypridle -c ~/.config/hypr/hypridle.conf
exec-once = systemctl --user import-environment WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && systemctl --user start hyprland-session.target
exec-once = [workspace 1] $terminal
exec-once = swaybg -i ~/.config/hypr/assets/3.jpg
exec-once = tmux setenv -g HYRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
