#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = touch $XDG_RUNTIME_DIR/hypr-first-shell && $terminal
exec-once = swaybg -i ~/.config/hypr/assets/pexels-robshumski-1903702.jpg
exec-once = tmux setenv -g HYRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
exec-once = ~/.config/hypr/scripts/touchpad-filter.py
