################
### PROGRAMS ###
################

$terminal = kitty -c ~/.config/hypr/kitty.conf
$fileManager = dolphin
$menu = wofi -s ~/.config/hypr/wofi.css --show drun
$browser = firefox
$calculator = speedcrunch
$ide = code
$ai_url = https://claude.ai
